services:
  api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile.dev

    ports:
      - "5000:8080"

    volumes:
      - ./src/Api:/src/Api
      - /src/Api/bin
      - /src/Api/obj